apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flink.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi